server:
    port: 9000
spring:
    application:
        name: CONFIGSERVER
    
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/nahuef5/ConfigServer_microservice
                    clone-on-start: true
                    