server:
    port: 1111

spring:
    application:
        name: GATEWAY-API
    cloud:
        gateway:
            routes:
                - id: USER
                  uri: lb://USER
                  predicates:
                      - Path=/users/**
                - id: HOTEL
                  uri: lb://HOTEL
                  predicates:
                      - Path=/hotels/**
                - id: RATING
                  uri: lb://RATING
                  predicates:
                      - Path=/ratings/**
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#Okta configuration for api gateway
okta:
    oauth2:
        issuer: https://dev-27553448.okta.com/oauth2/default
        audience: api://default
        client-id: 0oa99e8yohcitYDvO5d7
        client-secret: V4uIKsPj1nhveQIxG9hRytFDJsarXbJmWqv0Pp8g
        scopes: openid, profile, email, offline_access
            